import type { NextPage } from 'next'
import Head from 'next/head'
import DashboardLayout from '../components/app/DashboardLayout';
import ChatContainer from '../components/dashboard/ChatContainer';


const Home: NextPage = () => {
 
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <ChatContainer /> 
      </DashboardLayout>

    </div>
  )
}

export default Home
